name: Tests

on: [push]

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        ruby-version: ['2.3', '2.4', '2.5', '2.6']
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby-version}}
    - name: Run tests
      run: bundle exec rspec
